### PR TITLE
Added: dependabot config

### PR DESCRIPTION
**Pull request by GoliathLabs**
### Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

I already use Dependabot for many projects. With Dependabot it is relatively easy to stay up to date with the dependencies and packages used. Instead of always checking for updates manually, you can e.g. use the dependabot.yml configuration to tell Dependabot to check the project once a week for new releases of the npm packages that are used. If there are new updates, a new pull request is automatically created for them.

Since this procedure takes at least some work off my hands over at my projects, I wanted to ask if you would be up to using it as well. The configuration file is quickly created and dependabot then runs without further ado.

#### Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by dkgrieshammer** [comment]
Thx for the PR, we have Dependabot running over our Github Org but I'm happy to add it to the repo itself; 
one question I have is why is it observing a `/website`directory, shouldn't it be running on modules and src? I never used it on dir level, sry for my questions. Also maybe as a note, we still have storybook in the repo which is notoriously late on critical updates. Since it's not part of build I don't care that much but it's polluting dependabot constantly. Tbh I'm thinking of kicking it out even though I like the living styleguide thingy.

**Comment by GoliathLabs** [comment]
@dkgrieshammer yeah, sorry. I accidentally added the `/website` directory. Now it is observing `/`. We can try using dependabot with storybook for the time being. You can also tell dependabot to ignore certain packages from being updated which might come in handy here.

**Comment by GoliathLabs** [comment]
And please never apologise for asking questions. That's how we learn from each other and eventually correct our own mistakes :P

**Comment by GoliathLabs** [comment]
@dkgrieshammer any updates on this?

**Pull request closed without merging**
